FEAT-1: Switch to --postgresql-root option to do Postgres cart build
The previous option did not specify the PostgreSQL installation root.
That was to be specified in an undocumented environment variable. The
PostgreSQL RDKit cartridge build may still work without that environment
variable set, but it’s better to set it.

To have the installer build the PostgreSQL cartridge now you now specify
the --postgresql-root option and give it the root of your PostgresSQL
isntallation. For PostgreSQL 10 on Ubuntu that would be
/usr/lib/postgresql/10. You no longer need to set an environment
variable. The installer passes the PostgreSQL root location using the
cmake flag instead.

It also prints out instructions on how to install the PostgreSQL
cartridge once the RDKit installation is complete.

diff --git a/install-rdkit b/install-rdkit
--- a/install-rdkit
+++ b/install-rdkit
@@ -87,6 +87,18 @@ function main
         numpy_cmake_option="-D PYTHON_NUMPY_INCLUDE_PATH='${venv}/lib/python${python_version}/site-packages/numpy/core/include'"
     fi
 
+    if [ -z "${postgresql_root}" ]
+    then
+        build_psql='OFF'
+    else
+        if [ ! -d "${postgresql_root}" ]
+        then
+            die "ERROR: Invalid --postgresql-root. Directory ${postgresql_root} does not exist."
+        fi
+
+        build_psql='ON'
+    fi
+
     if [ ! -d "${install_dir}" ]
     then
         mkdir -p "${install_dir}"
@@ -112,6 +124,12 @@ function main
         libboost-regex-dev libboost-system-dev libboost-thread-dev \
         libboost-serialization-dev rdkit-data sqlite3 libsqlite3-dev \
         openbabel libboost-iostreams-dev
+    check_err $? 'Could not install required system packages.'
+
+    if [ ! -z "${postgresql_root}" ]
+    then
+        sudo apt-get install -y postgresql-server-dev-all
+    fi
     check_err $? 'Could not install required system packages.'
 
     case "${python_version}" in
@@ -167,6 +185,7 @@ function main
 
     mkdir -p "${install_dir}/build"
     cd "${install_dir}/build"
+    debug "Current directory for build: ${PWD}"
 
     case "${python_version}" in
         3.6)
@@ -180,12 +199,13 @@ function main
                 -D PYTHON_EXECUTABLE=/usr/bin/python3.6 \
                 $numpy_cmake_option \
                 -D RDK_BUILD_INCHI_SUPPORT=ON \
-                -D RDK_BUILD_PGSQL="${postgres_ext}" ..
+                -D RDK_BUILD_PGSQL="${build_psql}" \
+                -D PostgreSQL_ROOT="${postgresql_root}" ..
             ;;
         2.7)
             debug "Running cmake for Python ${python_version}..."
-            cmake -DRDK_BUILD_INCHI_SUPPORT=ON \
-                  -D RDK_BUILD_PGSQL="${postgres_ext}" ..
+            cmake -D RDK_BUILD_INCHI_SUPPORT=ON \
+                  -D RDK_BUILD_PGSQL="${build_psql}" ..
             ;;
     esac
 
@@ -193,7 +213,27 @@ function main
     make -j $cpu_cores
     make install
 
+    if [ ! -z "${postgresql_root}" ]
+    then
+        # Make sure the built RDKit cartidge files are readable by all so that
+        # they will be readable when the install script copies them into their
+        # system locations.
+        #
+        # Extract the filenames from the installer.
+        for file in $(grep -E '^cp ' "${install_dir}"/build/Code/PgSQL/rdkit/pgsql_install.sh | cut -d' ' -f 2 | tr -d '"')
+        do
+            chmod o=r "${file}"
+        done
 
+        # Modify the installer to make sure these permissions are preserved
+        # when the files are copied.
+        sed -i 's/^cp /cp --preserve=mode /' "${install_dir}"/build/Code/PgSQL/rdkit/pgsql_install.sh
+
+        # Make sure the PostgreSQL cartridge installer is executable.
+        chmod ug+x "${install_dir}"/build/Code/PgSQL/rdkit/pgsql_install.sh
+    fi
+
+    echo
     echo
     echo "RDKit installation is complete. To use it, enter the following commands. You should put these in your ~/.profile file, or in a script that you source when you want to use this RDKit installation."
     echo
@@ -203,6 +243,17 @@ function main
     echo 'export LD_LIBRARY_PATH'
     echo 'PYTHONPATH=$RDBASE:$PYTHONPATH'
     echo 'export PYTHONPATH'
+
+    if [ ! -z "${postgresql_root}" ]
+    then
+        echo
+        echo
+        echo 'To install the RDKit PostgreSQL cartridge enter the following commands.'
+        echo
+        echo 'sudo service postgresql stop'
+        echo "sudo ${install_dir}/build/Code/PgSQL/rdkit/pgsql_install.sh"
+        echo 'sudo service postgresql start'
+    fi
 }
 
 
@@ -250,7 +301,7 @@ function print_help
 		        Release_2018_09_1, Cyclica’s standard RDKit release.
 		
 		    -p, --python-version
-		        Version of Python to build for. Defaults to 3.6. Current
+		        Version of Python to build for. Defaults to 3.6. Currently
 		        supports 2.7, and 3.6.
 		
 		    -e, --virtual-env
@@ -259,10 +310,15 @@ function print_help
 		        activated it will default to that. It will ensure the virtual
 		        environment has numpy installed.
 		
-		    --postgres-extension
-		        Build RDKit with optional postgres cartridge. (Must have
-		        postgresql-server-dev installed PostgreSQL_ROOT environment
-		        variable set.)
+		    --postgresql-root
+		        Set this to the location where PostgreSQL is installed on your
+		        system and install-rdkit will build RDKit with the optional
+		        postgres cartridge. Once RDKit is built run the following to
+		        install the cartridge.
+		
+		        sudo service postgresql stop
+		        sudo ./build/Code/PgSQL/rdkit/pgsql_install.sh
+		        sudo service postgresql start
 		
 		    -d, --debug
 		        Print debugging output while running.
@@ -279,6 +335,10 @@ function print_help
 		
 		    # Download and compile Release_2018_09_1 for python 2.7 in /path/to/install/dir
 		    install-rdkit --python-version=2.7 --release=Release_2018_09_1 /path/to/install/dir
+		
+		    # Download and compile Release_2018_09_1 in /path/to/install/dir
+		    # with PostgreSQL cartridge built for PostgreSQL 10 on Ubuntu.
+		    install-rdkit --postgresql-root=/usr/lib/postgresql/10 /path/to/install/dir
 	EOF
 }
 
@@ -308,7 +368,7 @@ function parse_opts
     #   LONGOPTS=source:,debug,test
     #
     OPTIONS=r:p:e:dh
-    LONGOPTS=release:,python-version:,virtual-env:,postgres-extension,debug,help
+    LONGOPTS=release:,python-version:,virtual-env:,postgresql-root:,debug,help
 
     # Use ! and PIPESTATUS to get exit code with errexit set.
     # Temporarily store output to be able to check for errors.
@@ -351,9 +411,9 @@ function parse_opts
                 venv="${2}"
                 shift 2
                 ;;
-            --postgres-extension)
-                postgres_ext="ON"
-                shift
+            --postgresql-root)
+                postgresql_root="${2}"
+                shift 2
                 ;;
             -d|--debug)
                 DEBUG=true
@@ -373,11 +433,6 @@ function parse_opts
                 ;;
         esac
     done
-
-    if [ -z "${postgres_ext}" ]
-    then
-        postgres_ext="OFF"
-    fi
 
     if [ -z "${1}" ]
     then
